//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data_Layer.Repository
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class DMSEntities : DbContext
    {
        public DMSEntities()
            : base("name=DMSEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tbl_mst_dropdown> tbl_mst_dropdown { get; set; }
        public virtual DbSet<tbl_mst_filepath> tbl_mst_filepath { get; set; }
        public virtual DbSet<tbl_mst_Mapping> tbl_mst_Mapping { get; set; }
        public virtual DbSet<tbl_mst_Menu> tbl_mst_Menu { get; set; }
        public virtual DbSet<tbl_mst_Roles> tbl_mst_Roles { get; set; }
        public virtual DbSet<tbl_mst_section> tbl_mst_section { get; set; }
        public virtual DbSet<tbl_mst_Users> tbl_mst_Users { get; set; }
        public virtual DbSet<tbl_trx_accounts> tbl_trx_accounts { get; set; }
        public virtual DbSet<tbl_trx_office> tbl_trx_office { get; set; }
        public virtual DbSet<tbl_trx_purchase> tbl_trx_purchase { get; set; }
        public virtual DbSet<tbl_trx_recruitment> tbl_trx_recruitment { get; set; }
        public virtual DbSet<tbl_trx_dean> tbl_trx_dean { get; set; }
        public virtual DbSet<tbl_trx_FileDean> tbl_trx_FileDean { get; set; }
    
        public virtual ObjectResult<sp_appointment_summary_Result> sp_appointment_summary()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_appointment_summary_Result>("sp_appointment_summary");
        }
    
        public virtual ObjectResult<sp_datewise_desc10_Result> sp_datewise_desc10()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_datewise_desc10_Result>("sp_datewise_desc10");
        }
    
        public virtual ObjectResult<string> sp_getpath(Nullable<int> roleid)
        {
            var roleidParameter = roleid.HasValue ?
                new ObjectParameter("roleid", roleid) :
                new ObjectParameter("roleid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("sp_getpath", roleidParameter);
        }
    
        public virtual int sp_insert_fileupload(string fileno, string mode, Nullable<int> pages, string path, string uploadedBy)
        {
            var filenoParameter = fileno != null ?
                new ObjectParameter("Fileno", fileno) :
                new ObjectParameter("Fileno", typeof(string));
    
            var modeParameter = mode != null ?
                new ObjectParameter("mode", mode) :
                new ObjectParameter("mode", typeof(string));
    
            var pagesParameter = pages.HasValue ?
                new ObjectParameter("pages", pages) :
                new ObjectParameter("pages", typeof(int));
    
            var pathParameter = path != null ?
                new ObjectParameter("path", path) :
                new ObjectParameter("path", typeof(string));
    
            var uploadedByParameter = uploadedBy != null ?
                new ObjectParameter("uploadedBy", uploadedBy) :
                new ObjectParameter("uploadedBy", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_insert_fileupload", filenoParameter, modeParameter, pagesParameter, pathParameter, uploadedByParameter);
        }
    
        public virtual ObjectResult<sp_outsource_summary_Result> sp_outsource_summary()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_outsource_summary_Result>("sp_outsource_summary");
        }
    
        public virtual ObjectResult<sp_recruit_summary_Result> sp_recruit_summary()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_recruit_summary_Result>("sp_recruit_summary");
        }
    
        public virtual ObjectResult<sp_search_Result> sp_search(string mode, string fileno, string employeename)
        {
            var modeParameter = mode != null ?
                new ObjectParameter("mode", mode) :
                new ObjectParameter("mode", typeof(string));
    
            var filenoParameter = fileno != null ?
                new ObjectParameter("fileno", fileno) :
                new ObjectParameter("fileno", typeof(string));
    
            var employeenameParameter = employeename != null ?
                new ObjectParameter("employeename", employeename) :
                new ObjectParameter("employeename", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_search_Result>("sp_search", modeParameter, filenoParameter, employeenameParameter);
        }
    }
}
