//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data_Layer.Repository
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FoxOfficeEntities : DbContext
    {
        public FoxOfficeEntities()
            : base("name=FoxOfficeEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<PROPOSAL> PROPOSAL { get; set; }
        public virtual DbSet<PCMASTER> PCMASTER { get; set; }
        public virtual DbSet<PMASTER> PMASTER { get; set; }
    }
}
