//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data_Layer.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class PCMASTER
    {
        public string APRLNO { get; set; }
        public string DINP { get; set; }
        public string COCODE { get; set; }
        public string COOR1 { get; set; }
        public string COOR2 { get; set; }
        public string SNAME { get; set; }
        public string SNDES { get; set; }
        public string SCOM { get; set; }
        public string ADD1 { get; set; }
        public string ADD2 { get; set; }
        public string ADD3 { get; set; }
        public string SPANNUMBER { get; set; }
        public string STANNUMBER { get; set; }
        public string SGSTINNUMBER { get; set; }
        public string DEPT { get; set; }
        public string TITLE { get; set; }
        public Nullable<System.DateTime> STDATE { get; set; }
        public Nullable<System.DateTime> ENDDATE { get; set; }
        public Nullable<double> SANVALUE { get; set; }
        public Nullable<System.DateTime> SANDATE { get; set; }
        public Nullable<System.DateTime> EXTN { get; set; }
        public string EXTLETNO { get; set; }
        public Nullable<System.DateTime> EXTN1 { get; set; }
        public string EXTLETN1 { get; set; }
        public Nullable<double> STOROUT { get; set; }
        public Nullable<double> STORDEPT { get; set; }
        public Nullable<double> EUC { get; set; }
        public Nullable<double> CENTLFACI { get; set; }
        public Nullable<double> OUTFACI { get; set; }
        public Nullable<double> SALARY { get; set; }
        public Nullable<double> OTHERS { get; set; }
        public Nullable<double> ETOTAL { get; set; }
        public string PROJSTAT { get; set; }
        public string PROJREMA { get; set; }
        public string SLNO { get; set; }
        public Nullable<System.DateTime> RCPTDATE { get; set; }
        public string YEAR { get; set; }
        public string DEP_NAME { get; set; }
        public string N_YEAR { get; set; }
        public string AGENCY { get; set; }
        public string RB { get; set; }
        public string USTAT { get; set; }
        public Nullable<System.DateTime> ENT_DATE { get; set; }
        public string Loginname { get; set; }
        public string COOR3 { get; set; }
        public string COOR4 { get; set; }
        public string COOR5 { get; set; }
        public string CODEPT { get; set; }
        public string GOVT { get; set; }
        public string VERIFIED { get; set; }
        public Nullable<double> DOLL { get; set; }
        public string curr { get; set; }
        public string Remarks { get; set; }
        public string ProjectStatus { get; set; }
        public string InstID { get; set; }
    }
}
