//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data_Layer.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class PMASTER
    {
        public string APRLNO { get; set; }
        public string ENT_MONTH { get; set; }
        public string COOR_CODE { get; set; }
        public string COOR_CODE2 { get; set; }
        public string COOR_CODE3 { get; set; }
        public string COOR_CODE4 { get; set; }
        public string COOR_CODE5 { get; set; }
        public string COOR_CODE6 { get; set; }
        public string COOR_NAME { get; set; }
        public string COOR_NAME2 { get; set; }
        public string COOR_NAME3 { get; set; }
        public string COOR_NAME4 { get; set; }
        public string COOR_NAME5 { get; set; }
        public string COOR_NAME6 { get; set; }
        public string DEPT { get; set; }
        public string SPON { get; set; }
        public string SPON_AGEN { get; set; }
        public string TYPE { get; set; }
        public string LOCL_INT { get; set; }
        public string TITLE { get; set; }
        public Nullable<System.DateTime> START_DATE { get; set; }
        public Nullable<System.DateTime> CLOSE_DATE { get; set; }
        public Nullable<double> SANVALUE { get; set; }
        public string SAREFNO { get; set; }
        public Nullable<System.DateTime> SAREFDATE { get; set; }
        public string PROJ_REM { get; set; }
        public string PROJ_STATU { get; set; }
        public short SLNO { get; set; }
        public string YEAR { get; set; }
        public string DEPT_NAME { get; set; }
        public string DURATION { get; set; }
        public string REF_FIELD { get; set; }
        public Nullable<System.DateTime> DINP { get; set; }
        public string Loginname { get; set; }
        public string webinfo { get; set; }
        public string govt { get; set; }
        public string govt_type_MHRD { get; set; }
        public string govt_type_MINI { get; set; }
        public string govt_type_MINI_Name { get; set; }
        public string govt_type_IND { get; set; }
        public string govt_type_IND_Name { get; set; }
        public string Remarks_Sector { get; set; }
        public string verified { get; set; }
        public Nullable<short> PRONO { get; set; }
        public string Remarks { get; set; }
        public string ProjectType { get; set; }
        public string ProjectStatus { get; set; }
        public string InstID { get; set; }
        public string ProjectCategory { get; set; }
    }
}
