//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data_Layer.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class PROPOSAL
    {
        public Nullable<System.DateTime> DINP { get; set; }
        public int PRONO { get; set; }
        public Nullable<System.DateTime> DATE { get; set; }
        public Nullable<System.DateTime> datein { get; set; }
        public string TITLE { get; set; }
        public string DEPT { get; set; }
        public string CoorCode { get; set; }
        public string COOR_NAME { get; set; }
        public string COOR_NAME2 { get; set; }
        public string COOR_NAME3 { get; set; }
        public string AGENCY { get; set; }
        public string Scheme { get; set; }
        public string Applicantname { get; set; }
        public Nullable<double> VALUE { get; set; }
        public string DURATION { get; set; }
        public string Loginname { get; set; }
        public Nullable<System.DateTime> DispatchDate { get; set; }
        public string inst_id { get; set; }
    }
}
