//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data_Layer.Repository
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class RecruitEntities : DbContext
    {
        public RecruitEntities()
            : base("name=RecruitEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<designa> designas { get; set; }
        public virtual DbSet<OutSourcingDesignation> OutSourcingDesignations { get; set; }
        public virtual DbSet<AppointmentProject> AppointmentProjects { get; set; }
        public virtual DbSet<NEWADH> NEWADH { get; set; }
        public virtual DbSet<NEWREG> NEWREG { get; set; }
        public virtual DbSet<PART> PART { get; set; }
    
        public virtual ObjectResult<Department_Result> Department()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Department_Result>("Department");
        }
    }
}
