//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data_Layer.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_trx_FileDean
    {
        public long deanFile_trx_id { get; set; }
        public string Category { get; set; }
        public string SubCategory { get; set; }
        public string Source { get; set; }
        public Nullable<System.DateTime> ReceivedDt { get; set; }
        public string Remarks { get; set; }
        public int page_count { get; set; }
        public string file_path { get; set; }
        public string file_name { get; set; }
        public string uploadedBy { get; set; }
        public System.DateTime uploadedOn { get; set; }
        public Nullable<bool> is_active { get; set; }
    }
}
