//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data_Layer.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_mst_Menu
    {
        public int menuId { get; set; }
        public string menuName { get; set; }
        public int menuSubLevel { get; set; }
        public int menuLevel { get; set; }
        public string pageName { get; set; }
        public string controller { get; set; }
    }
}
