//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data_Layer.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_mst_Roles
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_mst_Roles()
        {
            this.tbl_mst_filepath = new HashSet<tbl_mst_filepath>();
            this.tbl_mst_Users = new HashSet<tbl_mst_Users>();
        }
    
        public int roleId { get; set; }
        public Nullable<int> sectionId { get; set; }
        public string roleName { get; set; }
        public Nullable<bool> is_active { get; set; }
        public string createdBy { get; set; }
        public System.DateTime createdOn { get; set; }
        public string updatedBy { get; set; }
        public Nullable<System.DateTime> updatedOn { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_mst_filepath> tbl_mst_filepath { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_mst_Users> tbl_mst_Users { get; set; }
        public virtual tbl_mst_section tbl_mst_section { get; set; }
    }
}
