//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data_Layer.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_trx_dean
    {
        public long dean_trx_id { get; set; }
        public string Agreement_No { get; set; }
        public short Year { get; set; }
        public string Partner { get; set; }
        public string Agreement_type { get; set; }
        public string Title { get; set; }
        public string Faculty { get; set; }
        public string DepartmentCode { get; set; }
        public Nullable<System.DateTime> Signed_date { get; set; }
        public Nullable<System.DateTime> Expiry_date { get; set; }
        public bool Followup { get; set; }
        public Nullable<int> FacultyID { get; set; }
        public int page_count { get; set; }
        public string file_path { get; set; }
        public string file_name { get; set; }
        public string uploadedBy { get; set; }
        public System.DateTime uploadedOn { get; set; }
        public Nullable<bool> is_active { get; set; }
    }
}
