//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data_Layer.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_mst_Users
    {
        public string userID { get; set; }
        public string userName { get; set; }
        public string userPassword { get; set; }
        public Nullable<int> roleId { get; set; }
        public Nullable<System.DateTime> last_login { get; set; }
        public Nullable<bool> is_active { get; set; }
        public string createdby { get; set; }
        public Nullable<System.DateTime> createdon { get; set; }
        public string updatedby { get; set; }
        public Nullable<System.DateTime> updatedon { get; set; }
    
        public virtual tbl_mst_Roles tbl_mst_Roles { get; set; }
    }
}
