//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data_Layer.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_trx_office
    {
        public long office_trx_id { get; set; }
        public string project_no { get; set; }
        public string doc_type { get; set; }
        public string file_path { get; set; }
        public string file_Namee { get; set; }
        public int page_count { get; set; }
        public string uploadedBy { get; set; }
        public Nullable<System.DateTime> uploadedOn { get; set; }
        public bool is_active { get; set; }
        public Nullable<bool> is_approved { get; set; }
        public string approvedBy { get; set; }
        public Nullable<System.DateTime> approvedOn { get; set; }
    }
}
