//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data_Layer.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_AppDev_FacultyDetails
    {
        public string EMPLOYEEID { get; set; }
        public string DISPLAYNAME { get; set; }
        public string EMPLOYEEDESIGNATIONNAME { get; set; }
        public string DEPARTMENTNAME { get; set; }
        public System.DateTime DateOfJoining { get; set; }
        public Nullable<System.DateTime> RetirementDate { get; set; }
        public string EmployeeStatus { get; set; }
        public string EMAIL { get; set; }
        public string DepartmentCode { get; set; }
        public string Phone { get; set; }
    }
}
